/* generated by tools/build/gen_embedded_web.py — DO NOT EDIT BY HAND */
#ifndef VLLM_EMBEDDED_WEB_H
#define VLLM_EMBEDDED_WEB_H

#include <stddef.h>

/* embedded admin.html (103472 bytes) */
const char *embedded_admin_html(size_t *len);

/* embedded chat.html (46902 bytes) */
const char *embedded_chat_html(size_t *len);

#endif /* VLLM_EMBEDDED_WEB_H */
