#!/usr/bin/env python3
"""Extract ggml_gemm_q4_0_4x4_q8_0 (asm kernel) verbatim from llama.cpp into a
standalone C function, so the ~480 lines of hand-written NEON sdot asm are
ported mechanically (zero transcription risk).

Source: llama_cpp/llama.cpp-master/ggml/src/ggml-cpu/arch/arm/repack.cpp
The asm block is the `__asm__ __volatile__( ... )` spanning lines 1852-2301.

Usage:
    python tools/extract_llama_asm.py <path/to/llama.cpp/repack.cpp> [out.c]

Regenerates tools/llama_gemm_q4_0_4x4_asm.c from the upstream llama.cpp file.
"""
import io
import os
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
    os.path.dirname(__file__), "..", "llama_cpp",
    "llama.cpp-master", "ggml", "src", "ggml-cpu",
    "arch", "arm", "repack.cpp")
OUT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
    os.path.dirname(__file__), "llama_gemm_q4_0_4x4_asm.c")

with open(SRC, "r", encoding="utf-8") as f:
    lines = f.readlines()

# 1-based inclusive boundaries of the __asm__ block inside
# void ggml_gemm_q4_0_4x4_q8_0(...)  (line 1826 .. 2305)
first = 1852  # "    __asm__ __volatile__("
last = 2301   # "    );"  (operand/clobber clause end)

block = "".join(lines[first - 1:last])

header = (
    "/* llama_gemm_q4_0_4x4_asm.c - mechanically extracted from llama.cpp\n"
    " * (ggml/src/ggml-cpu/arch/arm/repack.cpp, lines %d-%d), MIT license.\n"
    " * ggml_gemm_q4_0_4x4_q8_0: 4x4-tile Q4_0 x Q8_0 GEMM with hand-written\n"
    " * ARMv8.2 NEON asm (.inst sdot, 16 accs, software pipelined loads).\n"
    " *\n"
    " * Semantics (matches ggml_gemm_q4_0_4x4_q8_0_generic):\n"
    " *   s[row*bs + col] = sum_k W(row,k) * A(col,k)   (nr rows, nc cols)\n"
    " *   vx = block_q4_0x4[?][nb]  72B/block (4 weight rows x 32 q4 values)\n"
    " *   vy = block_q8_0x4[?][nb] 136B/block (4 tokens x 32 q8 values)\n"
    " *   rows are 4-interleaved: qs[k*16 + row*4 + i], scales d[4] f16 first.\n"
    " * Generated by tools/extract_llama_asm.py - DO NOT EDIT BY HAND. */\n"
    "#include <stddef.h>\n"
    "\n"
    "#if defined(__aarch64__) && defined(__ARM_NEON) && defined(__ARM_FEATURE_DOTPROD)\n"
    "static void st_gemm_q4_0_4x4_q8_0_neon(int n, float * __restrict s, size_t bs,\n"
    "                                       const void * __restrict vx,\n"
    "                                       const void * __restrict vy,\n"
    "                                       int nr, int nc) {\n"
    "    const void * b_ptr = vx;\n"
    "    const void * a_ptr = vy;\n"
    "    float * res_ptr = s;\n"
    "    size_t res_stride = bs * sizeof(float);\n"
    "    const int nb = n / 32;\n"
) % (first, last)

footer = (
    "    return;\n"
    "}\n"
    "#else\n"
    "static void st_gemm_q4_0_4x4_q8_0_neon(int n, float * s, size_t bs,\n"
    "                                       const void * vx, const void * vy,\n"
    "                                       int nr, int nc) {\n"
    "    (void)n; (void)s; (void)bs; (void)vx; (void)vy; (void)nr; (void)nc;\n"
    "}\n"
    "#endif\n"
)

with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(header)
    f.write(block)
    f.write(footer)

print("wrote %s (%d asm lines)" % (OUT, len(block.splitlines())))
