#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gen_embedded_web.py — embed admin.html / chat.html into the engine binary.

Reads  src/serve/admin.html and src/serve/chat.html, writes:
  src/serve/embedded_web.h   (declarations)
  src/serve/embedded_web.c   (byte arrays)

The engine serves the embedded copy when the HTML files are not deployed next
to the exe, so the shipped artifact is a single self-contained file. Re-run
this script after editing the HTML files.

Usage: python tools/gen_embedded_web.py
"""
import os
import sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(BASE, "src", "serve")
OUT_H = os.path.join(BASE, "include", "serve", "embedded_web.h")
OUT_C = os.path.join(SRC, "embedded_web.c")

FILES = [
    ("admin", "admin.html"),
    ("chat", "chat.html"),
    ("convert", "convert.html"),
]


def to_c_bytes(data: bytes) -> str:
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ", ".join("0x%02X" % b for b in chunk) + ",")
    return "\n".join(lines)


def main() -> None:
    arrays = []
    total = 0
    for name, fname in FILES:
        path = os.path.join(SRC, fname)
        if not os.path.isfile(path):
            print("ERROR: %s not found" % path)
            sys.exit(1)
        with open(path, "rb") as f:
            data = f.read()
        total += len(data)
        arrays.append((name, fname, data))

    with open(OUT_H, "w", encoding="utf-8") as f:
        f.write("/* generated by tools/gen_embedded_web.py — DO NOT EDIT BY HAND */\n")
        f.write("#ifndef VLLM_EMBEDDED_WEB_H\n#define VLLM_EMBEDDED_WEB_H\n\n")
        f.write("#include <stddef.h>\n\n")
        for name, fname, _ in arrays:
            f.write("/* embedded %s (%d bytes) */\n" % (fname, len(_)))
            f.write("const char *embedded_%s_html(size_t *len);\n\n" % name)
        f.write("#endif /* VLLM_EMBEDDED_WEB_H */\n")

    with open(OUT_C, "w", encoding="utf-8") as f:
        f.write("/* generated by tools/gen_embedded_web.py — DO NOT EDIT BY HAND */\n")
        f.write('#include "embedded_web.h"\n\n')
        for name, fname, data in arrays:
            f.write("static const unsigned char g_%s_html[] = {\n" % name)
            f.write(to_c_bytes(data))
            f.write("\n};\n")
            f.write("static const size_t g_%s_html_len = sizeof(g_%s_html);\n\n" % (name, name))
            f.write("const char *embedded_%s_html(size_t *len) {\n" % name)
            f.write("    if (len) *len = g_%s_html_len;\n" % name)
            f.write("    return (const char *)g_%s_html;\n" % name)
            f.write("}\n\n")
        f.write("/* %d bytes embedded total */\n" % total)

    print("wrote %s and %s (%d bytes total)" % (OUT_H, OUT_C, total))


if __name__ == "__main__":
    main()
